function runId = gnc_import_csv_to_sdi(csvFile, varargin)
%GNC_IMPORT_CSV_TO_SDI Import a GNC output CSV into Simulink Data Inspector.
%
%   runId = GNC_IMPORT_CSV_TO_SDI(csvFile) reads one CSV file generated by
%   the GNC framework and imports every numeric column except "time" into a
%   new Simulink Data Inspector run. By default, dotted CSV headers are
%   converted to Simulink-style block paths so SDI can show a collapsible
%   hierarchy. Existing SDI runs are not cleared.
%
%   runId = GNC_IMPORT_CSV_TO_SDI(csvFile, "Include", patterns) imports only
%   columns whose names contain at least one pattern. Matching is
%   case-insensitive. patterns can be a string, character vector, or string
%   array.
%
%   runId = GNC_IMPORT_CSV_TO_SDI(csvFile, "Open", false) imports the data
%   without opening the SDI window.
%
%   runId = GNC_IMPORT_CSV_TO_SDI(csvFile, "GroupBy", "none") keeps the full
%   CSV header as both the SDI source name and signal name. By default,
%   "GroupBy" is "component": a header such as
%   vehicle.dynamics.position_ecef.x is imported with block path
%   vehicle/dynamics/__signals__ and signal name position_ecef.x. The final
%   "__signals__" path element is only a virtual source leaf so SDI shows the
%   useful component level, vehicle/dynamics, in the Inspect table.
%
%   Examples:
%       cd tools/matlab
%       runId = gnc_import_csv_to_sdi("../../user/outputs/example.csv");
%       runId = gnc_import_csv_to_sdi("../../user/outputs/example.csv", ...
%                                    "Include", ["altitude", "mach"]);
%       runId = gnc_import_csv_to_sdi("../../user/outputs/example.csv", ...
%                                    "Open", false);
%       runId = gnc_import_csv_to_sdi("../../user/outputs/example.csv", ...
%                                    "GroupBy", "none");
%
%   Notes:
%       - This tool is intentionally standalone. Run it from this folder or
%         call it by full path; it does not require addpath.
%       - The CSV must contain a numeric "time" column.
%       - Units are not inferred or assigned.
%       - Non-numeric data columns are skipped with a warning.
%       - NaN and Inf values in signal columns are preserved.

    % Keep option parsing in one place so the import pipeline below can use
    % normalized strings and booleans without repeatedly checking MATLAB text
    % container variants.
    parser = inputParser;
    parser.FunctionName = mfilename;
    addRequired(parser, 'csvFile', @isTextScalar);
    addParameter(parser, 'Include', strings(0, 1), @isTextCollection);
    addParameter(parser, 'Open', true, @isScalarLogicalLike);
    addParameter(parser, 'GroupBy', 'component', @isTextScalar);
    parse(parser, csvFile, varargin{:});

    csvFile = char(string(parser.Results.csvFile));
    includePatterns = normalizeIncludePatterns(parser.Results.Include);
    openInspector = logical(parser.Results.Open);
    groupBy = normalizeGroupBy(parser.Results.GroupBy);

    if ~isfile(csvFile)
        error('GNC:ImportCsvToSDI:FileNotFound', ...
              'CSV file does not exist: %s', csvFile);
    end

    % Preserve the CSV headers exactly. Dotted names such as
    % vehicle.dynamics.altitude_m carry the component hierarchy that we later
    % map into SDI block paths.
    data = readtable(csvFile, 'VariableNamingRule', 'preserve');
    headers = string(data.Properties.VariableNames);
    timeIndex = find(headers == "time", 1);
    if isempty(timeIndex)
        error('GNC:ImportCsvToSDI:MissingTime', ...
              'CSV file must contain a "time" column.');
    end

    % The time column is the shared sample vector for every imported signal.
    % It is stricter than signal columns because SDI cannot place samples on
    % NaN or Inf timestamps.
    [timeValues, timeOk] = numericColumn(data.(data.Properties.VariableNames{timeIndex}));
    if ~timeOk
        error('GNC:ImportCsvToSDI:InvalidTime', ...
              'Column "time" must be numeric or fully convertible to numeric values.');
    end
    if any(~isfinite(timeValues))
        error('GNC:ImportCsvToSDI:InvalidTime', ...
              'Column "time" must not contain NaN or Inf values.');
    end

    signalIndexes = setdiff(1:numel(headers), timeIndex, 'stable');
    if ~isempty(includePatterns)
        % Include is a lightweight substring filter, meant for quick manual
        % inspection without changing the CSV or creating a separate manifest.
        selected = false(size(signalIndexes));
        lowerHeaders = lower(headers(signalIndexes));
        for i = 1:numel(includePatterns)
            selected = selected | contains(lowerHeaders, lower(includePatterns(i)));
        end
        signalIndexes = signalIndexes(selected);
    end

    if isempty(signalIndexes)
        error('GNC:ImportCsvToSDI:NoSignalsSelected', ...
              'No CSV data columns matched the requested selection.');
    end

    sourceNames = {};
    signalValues = {};
    skippedColumns = strings(0, 1);
    for index = signalIndexes
        % Each data column becomes one SDI signal. Non-numeric columns are
        % tolerated because future CSVs may contain tags or modes that are
        % useful to other tools but not directly plottable in SDI.
        signalName = headers(index);
        columnName = data.Properties.VariableNames{index};
        [values, ok] = numericColumn(data.(columnName));
        if ~ok
            skippedColumns(end + 1, 1) = signalName; %#ok<AGROW>
            warning('GNC:ImportCsvToSDI:SkippedNonNumeric', ...
                    'Skipping non-numeric CSV column: %s', signalName);
            continue;
        end
        if numel(values) ~= numel(timeValues)
            skippedColumns(end + 1, 1) = signalName; %#ok<AGROW>
            warning('GNC:ImportCsvToSDI:SkippedLengthMismatch', ...
                    'Skipping CSV column with %d value(s), expected %d: %s', ...
                    numel(values), numel(timeValues), signalName);
            continue;
        end

        [sourceName, sdiSignalName] = splitSdiSignalName(signalName, groupBy);
        series = timeseries(values(:), timeValues(:), 'Name', sdiSignalName);
        if groupBy == "component"
            % SDI only shows a useful subsystem tree when the signal carries a
            % SimulationData block path. The timeseries alone imports, but it
            % stays flat in the Inspect table.
            signal = Simulink.SimulationData.Signal;
            signal.Name = sdiSignalName;
            signal.Values = series;
            signal.BlockPath = Simulink.SimulationData.BlockPath(sourceName);
            sourceNames{end + 1} = sourceName; %#ok<AGROW>
            signalValues{end + 1} = signal; %#ok<AGROW>
        else
            sourceNames{end + 1} = sourceName; %#ok<AGROW>
            signalValues{end + 1} = series; %#ok<AGROW>
        end
    end

    importedSignalCount = numel(signalValues);

    if importedSignalCount == 0
        if isempty(skippedColumns)
            message = 'No numeric CSV data columns were available for import.';
        else
            message = sprintf('No numeric CSV data columns were available for import. Skipped: %s', ...
                              strjoin(cellstr(skippedColumns), ', '));
        end
        error('GNC:ImportCsvToSDI:NoSignalsImported', '%s', message);
    end

    [~, runName] = fileparts(csvFile);
    % The namevalue form keeps one source name beside each signal value. This
    % avoids bundling the CSV into a MATLAB dataset object that would add an
    % extra visible "dataset" layer in SDI.
    runId = Simulink.sdi.createRun(runName, 'namevalue', sourceNames, signalValues);

    if groupBy == "component"
        Simulink.sdi.setTableGrouping('Subsystems', 'DataHierarchy');
    end

    if openInspector
        Simulink.sdi.view;
    end
end

function ok = isTextScalar(value)
    % inputParser validators accept both legacy char vectors and modern string
    % scalars so the tool works naturally across MATLAB releases.
    ok = (ischar(value) && (isrow(value) || isempty(value))) || ...
         (isstring(value) && isscalar(value));
end

function ok = isTextCollection(value)
    ok = isTextScalar(value) || isstring(value) || iscellstr(value);
end

function ok = isScalarLogicalLike(value)
    ok = isscalar(value) && (islogical(value) || isnumeric(value));
end

function patterns = normalizeIncludePatterns(patterns)
    % Normalize Include to a column string array and drop empty patterns. An
    % empty result means "do not filter".
    if isempty(patterns)
        patterns = strings(0, 1);
        return;
    end
    if ischar(patterns)
        patterns = string({patterns});
    else
        patterns = string(patterns);
    end
    patterns = strtrim(patterns(:));
    patterns(patterns == "") = [];
end

function groupBy = normalizeGroupBy(groupBy)
    % Only two import shapes are supported deliberately: native flat CSV names
    % or component-oriented SDI hierarchy.
    groupBy = lower(strtrim(string(groupBy)));
    if groupBy ~= "component" && groupBy ~= "none"
        error('GNC:ImportCsvToSDI:InvalidGroupBy', ...
              'GroupBy must be "component" or "none".');
    end
end

function [sourceName, signalName] = splitSdiSignalName(csvHeader, groupBy)
    csvHeader = string(csvHeader);
    if groupBy == "none"
        sourceName = char(csvHeader);
        signalName = char(csvHeader);
        return;
    end

    parts = split(csvHeader, ".");
    if numel(parts) >= 3
        % Header convention:
        %   vehicle.dynamics.position_ecef.x
        % SDI path:
        %   vehicle/dynamics/__signals__
        % SDI signal:
        %   position_ecef.x
        %
        % The virtual leaf is intentional. SDI displays signals under the
        % parent subsystem of the source block, so this places the visible
        % group at the component level instead of adding field-level folders.
        pathParts = [parts(1:2); "__signals__"];
        sourceName = char(strjoin(pathParts, "/"));
        signalName = char(strjoin(parts(3:end), "."));
    elseif numel(parts) == 2
        % For shorter names, keep the first segment as the visible group and
        % the second as the signal name.
        pathParts = [parts(1); "__signals__"];
        sourceName = char(strjoin(pathParts, "/"));
        signalName = char(parts(2));
    elseif numel(parts) == 1
        % Single-token headers have no component prefix, so put them under a
        % generic group rather than fabricating a vehicle/component name.
        sourceName = 'signals/__signals__';
        signalName = char(parts(1));
    else
        sourceName = 'signals/__signals__';
        signalName = char(csvHeader);
    end
end

function [values, ok] = numericColumn(column)
    % Convert common MATLAB table column representations into a double column
    % vector. ok=false means the whole CSV column is non-numeric and should be
    % skipped; individual missing values remain NaN when conversion succeeds.
    ok = true;
    if isnumeric(column) || islogical(column)
        values = double(column(:));
        return;
    end

    if iscell(column)
        try
            raw = string(column(:));
        catch
            values = [];
            ok = false;
            return;
        end
    elseif isstring(column) || ischar(column) || iscategorical(column)
        raw = string(column(:));
    else
        values = [];
        ok = false;
        return;
    end

    raw = strtrim(raw);
    values = str2double(raw);
    % str2double returns NaN for both real NaN text and failed conversions, so
    % distinguish explicit NaN/Inf/missing text from genuinely nonnumeric data.
    missing = ismissing(raw) | raw == "";
    rawLower = lower(raw);
    explicitNaN = rawLower == "nan" | rawLower == "+nan" | rawLower == "-nan";
    explicitInf = rawLower == "inf" | rawLower == "+inf" | rawLower == "-inf" | ...
                  rawLower == "infinity" | rawLower == "+infinity" | rawLower == "-infinity";
    convertible = ~isnan(values) | explicitNaN | explicitInf | missing;
    ok = all(convertible);
    values(missing) = NaN;
end
